version: "3.9"
services:
  server:
    build: ./server
    image: s290168/oqm-server:second
    ports:
      - "3001:3001"
    networks:
      - webappnetwork
  client:
    build: ./client
    image: s290168/oqm-client:second
    ports:
      - "3000:3000"
    links:
      - "server:se"
    networks:
      - webappnetwork
networks:
    webappnetwork:
        driver: bridge