### login 1

POST http://localhost:3001/api/sessions/
Content-Type: application/json

{"username": "manager", "password": "password"}

### login 2

POST http://localhost:3001/api/sessions/
Content-Type: application/json

{"username": "totem", "password": "totem"}

### login 3

POST http://localhost:3001/api/sessions/
Content-Type: application/json

{"username": "counter2", "password": "counter2"}

### logout

DELETE  http://localhost:3001/api/sessions/current

###check login

GET http://localhost:3001/api/sessions/current/

###get ticket number

GET http://localhost:3001/api/ticket/

### insert ticket

POST http://localhost:3001/api/ticket/
Content-Type: application/json

{"service": "payment"}

###get services

GET http://localhost:3001/api/services

###get services

GET http://localhost:3001/api/nextCustomer?counter_id=3